version: '3.8'
services:
  legado-acl-service:
    build:
      context: ./legado-acl-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  # renegociacao-service: definido em docker-compose.yml (raiz)

  cobranca-service:
    build:
      context: ./cobranca-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  pagamento-service:
    build:
      context: ./pagamento-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  notificacao-service:
    build:
      context: ./notificacao-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
