server:
  port: 8085

spring:
  application:
    name: legado-acl-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    br.com.itau.recuperacao: DEBUG
